//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentPlanClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PaymentPlanClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Adress.
        /// </summary>
        internal static string LBTAddress_Url {
            get {
                return ResourceManager.GetString("LBTAddress_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Appointment.
        /// </summary>
        internal static string LBTAppointment_Url {
            get {
                return ResourceManager.GetString("LBTAppointment_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Complaint.
        /// </summary>
        internal static string LBTComplaint_Url {
            get {
                return ResourceManager.GetString("LBTComplaint_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Email.
        /// </summary>
        internal static string LBTEmail_Url {
            get {
                return ResourceManager.GetString("LBTEmail_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Login.
        /// </summary>
        internal static string LBTLoginClient_Url {
            get {
                return ResourceManager.GetString("LBTLoginClient_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /PaymentPlan?LoanId={0}.
        /// </summary>
        internal static string LbtPaymentPlanMakerClient_GetPaymentPlanType_Url {
            get {
                return ResourceManager.GetString("LbtPaymentPlanMakerClient_GetPaymentPlanType_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /PaymentPlan.
        /// </summary>
        internal static string LbtPaymentPlanMakerClient_MakeDraftPaymentPlan_api_PaymentPlan_Url {
            get {
                return ResourceManager.GetString("LbtPaymentPlanMakerClient_MakeDraftPaymentPlan_api_PaymentPlan_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /RefreshPaymentPlan.
        /// </summary>
        internal static string LbtPaymentPlanMakerClient_RefreshPaymentPlan_api_RefreshPayment_Url {
            get {
                return ResourceManager.GetString("LbtPaymentPlanMakerClient_RefreshPaymentPlan_api_RefreshPayment_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://fb.lbtvarlik.com.tr/webcentricapi/api.
        /// </summary>
        internal static string LBTPaymentPlanMakerClient_ServiceUrl {
            get {
                return ResourceManager.GetString("LBTPaymentPlanMakerClient_ServiceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Phone.
        /// </summary>
        internal static string LBTPhone_Url {
            get {
                return ResourceManager.GetString("LBTPhone_Url", resourceCulture);
            }
        }
    }
}
